name: sif_downscaling_cdse_stac
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cartopy=0.25.0=py313h08cd8bf_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cf-xarray=0.10.9=pyhd8ed1ab_0
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - cftime=1.6.4=py313h29aa505_2
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - contourpy=1.3.3=py313h7037e92_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - esmf=8.9.0=mpi_mpich_h50cdae2_103
  - esmpy=8.9.0=pyhc455866_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - geos=3.14.1=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - giflib=5.2.2=hd590300_0
  - google-crc32c=1.7.1=py313h74173ec_1
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=mpi_mpich_h02efad0_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=4_h0358290_openblas
  - libclang-cpp21.1=21.1.7=default_h99862b1_1
  - libclang13=21.1.7=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libfabric=2.3.1=ha770c72_1
  - libfabric1=2.3.1=h6c8fc0a_1
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgdal-core=3.10.3=hd23061b_26
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h32235b2_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_15
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=4_h47877c9_openblas
  - libllvm21=21.1.7=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=mpi_mpich_h84cb79c_3
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpnetcdf=1.14.1=mpi_mpich_h3dbf9f6_100
  - libpng=1.6.51=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libuuid=2.41.2=h5347b49_1
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.45.1=py313hdd307be_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - matplotlib=3.10.8=py313h78bf25f_0
  - matplotlib-base=3.10.8=py313h683a580_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h05a5f5f_0
  - mpi=1.0.1=mpich
  - mpich=4.3.2=h79b1c89_100
  - msgpack-python=1.1.2=py313h7037e92_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - netcdf-fortran=4.6.2=mpi_mpich_hf41eadc_2
  - netcdf4=1.7.3=nompi_py313hfae5b86_100
  - numba=0.62.1=py313h7afe1cf_1
  - numcodecs=0.16.5=py313h08cd8bf_0
  - numpy=2.3.5=py313hf6604e3_0
  - openeo=0.46.0=pyhd8ed1ab_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_2
  - parallelio=2_6_7=mpi_mpich_h66c247d_100
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py313h80991f8_2
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - proj=9.7.1=h99ae125_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py313h77f6078_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pyside6=6.9.3=py313h85046ba_1
  - pysocks=1.7.1=pyha55dd90_7
  - pystac=1.14.1=pyhd8ed1ab_0
  - python=3.13.10=hc97d973_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rasterio=1.4.3=py313h6bd603e_3
  - rdma-core=60.0=hecca717_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rioxarray=0.20.0=pyhd8ed1ab_1
  - scipy=1.16.3=py313h11c21cd_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py313had47c43_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.51.1=hbc0de68_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py313h07c4f96_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucx=1.19.0=h63b5c0b_5
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py313h07c4f96_1
  - xarray=2025.1.1=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.3.0=h988505b_0
  - xesmf=0.9.2=pyhd8ed1ab_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zarr=3.1.5=pyhcf101f3_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstandard=0.25.0=py313h54dd161_1
  - zstd=1.5.7=hb78ec9c_6
